disable_ligatures never
cursor_shape block
cursor_shape_unfocused beam 
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
font_size 14
mouse_map ctrl+shift+left press grabbed discard_event
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled
tab_title_template " {title}-{index} "
editor nvim
close_on_child_death yes
allow_remote_control no

map alt+1 no_op
map alt+2 no_op
map alt+3 no_op
map alt+4 no_op
map alt+5 no_op
map alt+6 no_op
map alt+7 no_op
map alt+8 no_op
map alt+9 no_op
map alt+0 no_op

background #16151f
